add subgroup size control
plaidml/plaidml pull request #1361
Opened 2020-09-15 21:42 UTC by adstraw

2020-09-15 21:48 UTC, adstraw commented on pmlc/rt/vulkan/vulkan_invocation.cc
> +  subgroupSizeInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
Changed intentionally from VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES to VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO based on debug results from @jbruestle

2020-09-15 21:55 UTC, jbruestle requested changes

2020-09-15 21:55 UTC, jbruestle commented on pmlc/conversion/gpu/gpu_to_vulkan.cc
> +  // TODO: select subgroup size based on the previous passes and some special
So technically we cannot set subgroupSize for non-subgroup kernels to 8 if the number of threads is not divisible by 8.  I think we need to grab the attribute on the kernel launch and pass that down.  non-subgrouped kernels should either have no attribute or have an attribute set to 1 depending on lowering stage.

2020-09-15 21:55 UTC, jbruestle commented on pmlc/rt/vulkan/vulkan_invocation.cc
> +  if (device->isExtensionSupported("VK_EXT_subgroup_size_control"))
Similar to above, we probably need to skip specifying subgroup size if the value is 1 (or the extension is not supported).

2020-09-18 13:38 UTC, abialas1 commented
Checked in some lowerings, however still missing the SCF->GPU part that is within llvm upstream. Working on the best way to have it added there.

2020-09-23 13:51 UTC, closed without merging