Fix potential bug if outStrides is empty in pad_range
plaidml/plaidml pull request #1429
Opened 2020-10-02 22:32 UTC by shiyao00

2020-10-02 22:34 UTC, flaub commented on pmlc/dialect/tile/transforms/pad_ranges.cc
> +    if (!outStrides || outStrides->strides.size() == 0) {
Use `strides.empty()`. I feel like maybe we should make `util::computeStrideArray` consistently return either nothing or an empty array but not both.  @jbruestle ?

2020-10-02 22:34 UTC, shiyao00 commented
For normalize, the output is zero dimensional. In this case, it accesses outStrides->strides[i] later which is a bug.

2020-10-02 23:05 UTC, jbruestle requested changes
This is a bug, but this is the wrong bugfix.  The bug is here: https://github.com/plaidml/plaidml/blob/plaidml-v1/pmlc/util/strides.cc#L62.  
StrideArray(0) should be StrideArray(map.getNumDims(), 0).

2020-10-03 05:08 UTC, flaub approved these changes

2020-10-03 05:39 UTC, merged