pml-ocl-gen resnet50
plaidml/plaidml pull request #1485
Opened 2020-10-20 18:58 UTC by drgone

2020-10-20 19:13 UTC, jbruestle submitted a review, later dismissed

2020-10-21 22:48 UTC, flaub approved these changes

2020-10-21 23:04 UTC, adstraw requested changes
please adjust thresholds in plan.yml so that we are gating performance for both vk and ocl gen resnet50 runs.  golden value is 21ms.  my thought is to set thresholds to 0.33 for vk and ocl.  this would mean we gate vk and ocl commits for 3x the golden.

2020-10-21 23:09 UTC, adstraw approved these changes
LGTM

2020-10-22 08:23 UTC, flaub approved these changes

2020-10-22 08:24 UTC, merged