Make stdx/llvm lowering type-agnostic
plaidml/plaidml pull request #1784
Opened 2021-05-27 16:18 UTC by jd-bartlett96

2021-05-27 23:54 UTC, tzerrell reviewed
Is this sufficient to fix the failed lowerings you were hitting? Or does this get you one step further and then fail (e.g. perhaps an intrinsic does not exist for `resType`)?

2021-05-28 17:03 UTC, jd-bartlett96 commented
> Is this sufficient to fix the failed lowerings you were hitting? Or does this get you one step further and then fail (e.g. perhaps an intrinsic does not exist for `resType`)?

This resolves the failures I was seeing, which were all trying to lower a F16 type, which does appear to have an existing intrinsic. Should a check also be included to check that the intrinsic exists and cast into/out of a working type if it does not?

2021-05-28 17:21 UTC, tzerrell commented
> > Is this sufficient to fix the failed lowerings you were hitting? Or does this get you one step further and then fail (e.g. perhaps an intrinsic does not exist for `resType`)?
> 
> This resolves the failures I was seeing, which were all trying to lower a F16 type, which does appear to have an existing intrinsic. Should a check also be included to check that the intrinsic exists and cast into/out of a working type if it does not?

Great! Adding such a check would be ideal, but considering the previous crash it would still be an improvement to land this as-is if there are difficulties with that.

2021-05-28 19:33 UTC, flaub commented
Adding a lit test might also be good

2021-07-01 18:17 UTC, flaub commented on pmlc/conversion/stdx_to_llvm/tests/elementwise.mlir
> +module {
You can drop the enclosing `module`

2021-07-01 18:17 UTC, tzerrell commented
I added lit tests; this needs a review from someone other than me.

One particular concern: In the lit test for `pow` on `i32` data, it lowered to `powf` -- I don't know enough about LLVM to know if this is correct or buggy, but the lit test as-written is expecting `powf` to be produced.

2021-07-01 18:20 UTC, flaub commented
I'm also concerned about that. I think a further lowering would fail or worse crash if we don't have proper data types. 

FYI, upstream now has the pass I think we want: https://github.com/plaidml/llvm-project/blob/develop/mlir/include/mlir/Conversion/MathToLibm/MathToLibm.h

2021-07-01 18:47 UTC, tzerrell requested changes
Thanks for the reference! Marking as "Request changes" as this is likely broken in the integer case.

2022-01-14 02:03 UTC, closed without merging