Update LLVM to latest upstream
plaidml/plaidml pull request #1805
Opened 2021-06-21 16:02 UTC by vinograd47

Related PR: https://github.com/plaidml/llvm-project/pull/42

2021-06-25 17:05 UTC, earhart approved these changes

2021-06-25 18:47 UTC, flaub requested changes
We need to bump the pointer forward. We need to land the llvm-project PR before landing this one.

2021-06-26 15:37 UTC, vinograd47 commented
@flaub Done

2021-06-28 05:35 UTC, flaub approved these changes

2021-06-28 05:58 UTC, merged